### ISSUE TITLE
BDD tesztek elkészítése

### ISSUE THREAD

**Issue by 1998mp** [BME-MIT-IET/mmamata-iet-2020#18]
A BDD tesztek elkészítése, BDD tesztek segítségével a szoftver helyes működésének a vizsgálata.

**Comment by tkonyves** [comment]
cars.rdf és cars.ttl törölve lett. Matyival egyeztetve, ezeket visszamásoltam a bdd-test branch-en.

**Comment by tkonyves** [comment]
Pár dolgot még javítottunk a Codacy jelzései alapján.

A Codacy még az osztályok és metódusok neveire is panaszkodik, de úgy döntöttünk, hogy ezek egyelőre maradnak, hiszen megfelelnek a Cucumber által javasolt konvenciónak.
